### ISSUE TITLE
Validation error in OJS 3.3.0.11

### ISSUE THREAD

**Issue by jvoix** [ualbertalib/ojsxml#12]

**Comment by jvoix** [comment]
This amazing little scripts generates the XML file successfully but the validation to OJS 3.3.0.11 fails at the validation, with the following error: 
`    Element '{http://pkp.sfu.ca}author': Missing child element(s). Expected is ( {http://pkp.sfu.ca}email ).`
![OJS 3 3 0 11 Native XML Plugin Error](https://github.com/ualbertalib/ojsxml/assets/64561242/0c5ae0e7-8462-47f5-896d-3db14765d2cc)

I have checked that each  "author" element has a "email" child element...

Any suggestions?

**Comment by devroid-roo** [comment]
hi @jvoix , is it possible for you to let me know what were the varibale that you set up in config.ini file?

**Comment by jvoix** [comment]
Things turn to be actually related to one author entry not having a proper email, hence that was not imported properly by OJS. Your amazing script is really not the issue and I apologize for this report.

**Comment by devroid-roo** [comment]
hi @jvoix , i am not the author of this script. i just have some questions can you please help:

can you please share the varibale that you set up in config.ini ? 
did you run this script in local machine or in server ?

**Comment by jvoix** [comment]
Sorry for the mistake.

I ran this on a Ubuntu laptop. The only variable I changed in the .ini
file was the file path for the log files.
Cordialement,


Jérémie

-- 


 
  

Logo officiel ETS

  

Jérémie Voix, ing., Ph.D.   |  Professeur titulaire
Chaire de recherche industrielle CRSNG-EERS en technologies
intra-auriculaires




École de technologie supérieure  |  1100, rue Notre-Dame Ouest 
|  Montréal (Qc) Canada  |  H3C 1K3



Tél.:  (514) 396-8437   |  Courriel ***@***.***  | 
critias.etsmtl.ca [1]



_L'ÉTS est une constituante du réseau de l'Université du Québec___

 
 

  



--- Original message follows ---
Subject: Re: [ualbertalib/ojsxml] Validation error in OJS 3.3.0.11
(Issue #12)
From: "devroid-roo" 
To: "ualbertalib/ojsxml" 
CC: "Voix, Jérémie" , "Mention" 
Date: 2023-10-06 9:42












hi @jvoix [2] , i am not the author of this script. i just have some
questions can you please help:



can you please share the varibale that you set up in config.ini ?
did you run this script in local machine or in server ?



—
Reply to this email directly, view it on GitHub [3], or unsubscribe
[4].
You are receiving this because you were mentioned.Message ID: 





Links:
------
[1] http://critias.etsmtl.ca/
[2] https://github.com/jvoix
[3]
https://github.com/ualbertalib/ojsxml/issues/12#issuecomment-1750703862
[4]

**Comment by devroid-roo** [comment]
thanks @jvoix . i converted csv file and then tried to import using native xml plugin however i didn't get anything 
![Screen Shot 2023-10-06 at 3 18 31 PM](https://github.com/ualbertalib/ojsxml/assets/147104585/2e2c256a-2ac5-4484-8436-b6fa776ec3ae)

**Comment by devroid-roo** [comment]
@jvoix thanks a lot , i was able to import the xml file however the cover images don't go through. i tried 2 different imports. were you able to import the cover images?

**Comment by jvoix** [comment]
Hello,

Actually NO, I just imported the PDF files of the articles.
Cordialement,


Jérémie

-- 


 
  

Logo officiel ETS

  

Jérémie Voix, ing., Ph.D.   |  Professeur titulaire
Chaire de recherche industrielle CRSNG-EERS en technologies
intra-auriculaires




École de technologie supérieure  |  1100, rue Notre-Dame Ouest 
|  Montréal (Qc) Canada  |  H3C 1K3



Tél.:  (514) 396-8437   |  Courriel ***@***.***  | 
critias.etsmtl.ca [1]



_L'ÉTS est une constituante du réseau de l'Université du Québec___

 
 

  



--- Original message follows ---
Subject: Re: [ualbertalib/ojsxml] Validation error in OJS 3.3.0.11
(Issue #12)
From: "devroid-roo" 
To: "ualbertalib/ojsxml" 
CC: "Voix, Jérémie" , "Mention" 
Date: 2023-10-10 11:31












@jvoix [2] thanks a lot , i was able to import the xml file however
the cover images don't go through. i tried 2 different imports. were
you able to import the cover images?



—
Reply to this email directly, view it on GitHub [3], or unsubscribe
[4].
You are receiving this because you were mentioned.Message ID: 





Links:
------
[1] http://critias.etsmtl.ca/
[2] https://github.com/jvoix
[3]
https://github.com/ualbertalib/ojsxml/issues/12#issuecomment-1755696377
[4]
