### ISSUE TITLE
cover images don't go through

### ISSUE THREAD

**Issue by devroid-roo** [ualbertalib/ojsxml#13]
hi @jhennig , @ewhanson ,

first of all thanks for this amazing tool. I was able to convert csv into xml and then import the xml file using NATIVE XML PLUGIN however the cover image doesn't show up on ojs side for the article. 

i have followed all the instructions provided: 
1. cover images place them in the issue_cover_images directory
2. cover image is in .jpg
3. both cover_image_filename and cover_image_alt_text must be included

Please let me know if there is something that we need to do.

Thanks a lot

**Comment by jhennig** [comment]
Do you get the "covers" xml output?  It should look something this:
....
   </section>
  </sections>
  <covers>
   <cover locale="en_US">
    <cover_image>cover_image.png</cover_image>
    <cover_image_alt_text>my Alt Text</cover_image_alt_text>
    <embed encoding="base64">... .... ... ==</embed>
   </cover>
  </covers>
<articles .....
....

**Comment by devroid-roo** [comment]
hi @jhennig good news, the cover images are being imported now. i tested twice and can see cover images in submissions

**Comment by devroid-roo** [comment]
hi @jhennig good news, the cover images are being imported now. i tested twice and can see cover images in submissions
